### ISSUE TITLE
GeForce Now Input Delay

### ISSUE THREAD

**Issue by strexgth** [hmlendea/geforcenow-electron#38] opened 2021-02-23 16:00 UTC
Hi, I am currently using Linux Mint 20.1 and I am getting a strong input delay whilst playing Fortnite Battle Royale. 

Does anyone know how to fix this issue?

**Comment by hmlendea** [comment] 2021-02-25 10:31
Duplicate of #31 

Hi, this seems to affect quite a few users, espeically in input-sensitive games where it is much more noticeable. This seems to be a more general issue with Electron on Linux and not really something that I can fix in this project, though I am still trying to find solutions.

Some users reported though that while using Wayland instead of X11 the lag is much less of an issue or not at all.

**Comment by hmlendea** [comment] 2021-02-25 10:32
I am going to close this issue and further comments/replies can be added on #31

**Closed by hmlendea** 2021-02-25 10:32 UTC

**Comment by strexgth** [comment] 2021-02-25 13:33
Okay, thank you.
