### ISSUE TITLE
Web page instead of an app

### ISSUE THREAD

**Issue by SylEleuth** [hmlendea/geforcenow-electron#71] opened 2021-08-24 21:13 UTC
I haven't been using it for some time and today when I opened it I was greeted with nvidia "geforce now" web page (which is unsupported) instead of usual list of games I can play. I've looked everywhere, some link maybe but it's just ordinary web page, if I login I will see my account and all options, I can even go deeper and open any other page on nvidia site.
I deleted all config folders and nothing happened.
Is it me doing something wrong?
I'm on Manjaro, installed through https://aur.archlinux.org/packages/geforcenow-electron/

![Screenshot_20210824_220745](https://user-images.githubusercontent.com/33354262/130690209-918df04d-c47a-4345-b205-9d9f0efe1174.png)

**Comment by Melon-Bread** [comment] 2021-08-24 23:48
Duplicate of #70

**Comment by hmlendea** [comment] 2021-08-25 12:32
Closing. Discussions will continue on #70

**Closed by hmlendea** 2021-08-25 12:32 UTC
