### ISSUE TITLE
ESC key should not be a un-fullscreen shortcut, it should be something else, or alt-tab only

### ISSUE THREAD

**Issue by goofyseeker311** [hmlendea/geforcenow-electron#33] opened 2021-01-03 13:20 UTC
i dont wish my recordings to be messed by resizing of the screen, when not wanted, but moving in the game menus

**Comment by hmlendea** [comment] 2021-01-06 08:29
Hello,

Are you using the latest version?

**Comment by goofyseeker311** [comment] 2021-01-07 12:53
i deleted the whole operating system, but the latest snap what was in the store

**Comment by hmlendea** [comment] 2021-01-08 09:47
Yeah... the version on the snap store is a bit outdated :(
The ESC key issue was addressed since that version

**Comment by hmlendea** [comment] 2021-01-12 12:49
Closing this as so far it cannot be reproduced on the latest version

**Closed by hmlendea** 2021-01-12 12:49 UTC
Labels: invalid, outdated-installation
