### ISSUE TITLE
[BUG] Couldn't sign you in using Google SSO

### ISSUE THREAD

**Issue by markpendlebury** [hmlendea/geforcenow-electron#99] opened 2021-12-06 08:33 UTC
**Describe the bug**
When attempting to login to my account, entering my google account details i'm given the following error:

`Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.`

**To Reproduce**
1. Open Geforce Now Electron
2. Click Log In (top right)
3. In the new window, click "Nvidia"
4. Then on the login page select "Log in with Google"
5. Enter my google account email address and press next
6. Error

**Expected behavior**
After entering my google email address it should ask for a password then log me in to my nvidia account

**System information:**
- OS: Manjaro Linux x86_64 
- Host: X570 AORUS ELITE -CF 
- Kernel: 5.13.19-2-MANJARO 
- Resolution: 5120x1440 
- DE: Plasma 5.23.3 
- WM: KWin 
- CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz 
- GPU: NVIDIA GeForce RTX 2080 Rev. A 
- Memory: 4245MiB / 32046MiB 
- Installation Method: AUR (via pamac)
- Version: 1.1.12-1

**Additional context**
N/A

**Comment by hmlendea** [comment] 2021-12-06 13:30
Duplicate of #50, #69, #49

**Closed** 2022-03-18 14:34 UTC
Labels: duplicate, dependencies, nice-to-have, unfixable
