### ISSUE TITLE
Login Unsuccessful. We are sorry to report we were unable to log you into GeForce NOW.

### ISSUE THREAD

**Issue by 3nuc** [hmlendea/geforcenow-electron#44] opened 2021-04-04 10:45 UTC
1. Download latest release's zip on Arch Linux (geforcenow_1.1.0_linux.zip)  or Windows 10 (npm install from repo)
2. Run the launcher ./geforcenow (or npm start on Windows 10)
3. Try to log in - in my case it opens a new window saying 'you'll be logged in automatically in 5 seconds' (I logged in before with the same error I'm reporting) then it says:  
```
Login unsuccesful
We are sorry to report we were unable to log you into GeForce NOW. Please try again
[Close] [Retry]
```

However login works on:
1. Lutris launcher for GeForce NOW (Arch Linux)
2. Google Chrome (both Arch and Windows 10)
3. Windows 10 desktop client

Arch Linux output:
```sh
t430 :: ~/Downloads » ./geforcenow
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
GeForce NOW
GeForce NOW
NVIDIA
Sign in with NVIDIA
NVIDIA GeForce NOW
```

The libva error is probably because I'm on an Intel HD4000 graphics card - but the app launches fine nonetheless and I can proceed until the "Login Unsuccesful" modal. Windows 10 output is the same just that it doesn't have the libva error, so it's probably not that anyways.

**Comment by 3nuc** [comment] 2021-04-04 11:22
I added 
```js
  globalShortcut.register("Super+Shift+I", () => {
    BrowserWindow.getAllWindows().forEach((__window) => {
      __window.toggleDevTools();
    })
  });
```
to the app to see what's happening in the main and login windows.

The login window sends the login data and it receives a normal 302 request with a location header of the following format:
```
https://play.geforcenow.com/redirect/starfleet-oauth-redirect.html?ui_locales=en_US&nonce=[nonce here]&token_type=Bearer&expires_in=3600&access_token=[access_token here]
```
This looks like a "everything is ok" request to me. If it was wrong the 302 would redirect to some redirect?error="some_error_id" or whatever.

I'm suspecting the main window's (the one with the games, not the login window) service worker fails to read the new login data somehow.

**Comment by fenrave** [comment] 2021-04-07 00:33
Hi, having this exact issue with the login, here's what the terminal shows for me.

In case its important, I am on the latest version of Ubuntu studio, and I did install it via snapd, though given the nature of snaps I'm not sure if my OS really has much to do with it in that regard.

```bash
fenrave@fenrave-ms7b79:~$ geforcenow 
Gtk-Message: 19:24:43.564: Failed to load module "colorreload-gtk-module"
GeForce NOW
GeForce NOW
NVIDIA
Sign in with NVIDIA
GeForce NOW
NVIDIA
Sign in with NVIDIA
NVIDIA GeForce NOW
GeForce NOW
NVIDIA
Sign in with NVIDIA
Error occurred in handler for 'GUEST_WINDOW_MANAGER_WINDOW_METHOD': Error: Invalid guestId: 3
    at electron/js2c/browser_init.js:193:1580
    at electron/js2c/browser_init.js:201:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10005)
    at Object.emit (events.js:315:20)
fenrave@fenrave-ms7b79:~$ ```

No way to brute-force it either by selecting automatic login, It'll just tell you the same thing.

**Comment by karpaz** [comment] 2021-04-07 20:37
Hello, I have this issue too.

**Comment by dubigrasu** [comment] 2021-04-08 10:10
Same issue here.

**Comment by cohaereo** [comment] 2021-04-08 14:59
Same here

**Comment by orangemn6** [comment] 2021-04-09 16:23
same for me

**Comment by hmlendea** [comment] 2021-04-09 16:27
Does instaling a vaapi driver fix the problem?
E.g. for Intel, on Arch Linux the package is `intel-media-driver`, Ubuntu I think has `intel-vaapi-driver`

**Comment by hmlendea** [comment] 2021-04-09 16:47
Is any of you running this app for the first time ever on that system?

Is any of you simply having this problem after an update, while the account was sucessfully logged in prior to the update?

Does deleting `~/.config/GeForce NOW` and trying again help?

**Comment by uncon** [comment] 2021-04-09 17:29
I am running Arch, have community/intel-media-driver (21.1.3-1) installed, and have tried removing "~/.config/GeForce NOW" to no avail.

- Which version did you install? (snap, deb, other...)
    - geforcenow-electron in AUR
- Is this the first time you run this app on that system?
    - Yes
- Is this happening only after updating the app, while the account was sucessfully logged in prior to the update?
    - No; I have only recently (after the most recent update) tried this app
- Does deleting ~/.config/GeForce NOW and trying again help?
    - No

**Comment by dubigrasu** [comment] 2021-04-09 18:59
I tried both the appimage and deb versions.
Is not the first time I use this app.
It did worked before the update.
Deleting ~/.config/GeForce NOW doesn't work.

What works though is: use a previous version (1.0.9) to login, close it and then immediately start the current version (1.1.0).
I only tested this with the appimage versions, but this way I managed to get connected.

**Comment by Zimtir** [comment] 2021-04-12 21:38
Arch & Wayland Sway + X11 libs 

Deleting ~/.config/GeForce NOW doesn't work.
```
Login unsuccesful
We are sorry to report we were unable to log you into GeForce NOW. Please try again
[Close] [Retry]
```

**Comment by ABN-Speed** [comment] 2021-04-12 22:39
Ubuntu 20.04. I'm using the 1.1.0 .deb. 

Also, oddly enough, the 1.1.0 from popey on the snap store was working for me when upgrading for previous version. I remained logged in. However, when I logged out, it wouldn't log me back in. 

This is a regression, as installing the 1.0.8 version logs me in. I then upgrade to 1.1.0 and am still logged in.

**Comment by hmlendea** [comment] 2021-04-14 16:07
Successfully reproduced the issue and confirmed this as a regression due to the latest `electron` version, not the hardware acceleration.

I'm still debating what approach should I take, but as a last resort I can temporarily downgrade `electron` to `11.4.2`

**Comment by hmlendea** [comment] 2021-04-14 17:08
Version `1.1.1` that fixes this issue just got released.

I will close this thread. If any more login issues occur, please reopen.

**Closed by hmlendea** 2021-04-14 17:08 UTC
Labels: bug, mustfix
