### ISSUE TITLE
Google Account login fails due to unsecure browser

### ISSUE THREAD

**Issue by ResonantFilter** [hmlendea/geforcenow-electron#50] opened 2021-04-28 08:16 UTC
I begin by thanking all the contributors that work on this project.
I wanted to point out that if the geforce now account is a Google account linked to the service, the login will fail due to the fact that Google considers the browser opened by the application as unsecure.

Thanks again for your work.

**Comment by D3SOX** [comment] 2021-04-28 11:17
Duplicate of #49

**Comment by hmlendea** [comment] 2021-04-28 11:20
Yes, Google does indeed consider all Electron apps as "unsecure browsers".

I will allocate some time to study the ToS more and see if there is any way I can make the GAuth work **without** breaking the ToS. There certainly are ways to make it work (some Electron apps do it successfully), but I want to make sure it's ok and safe for the end-users

**Closed** 2021-04-28 11:20 UTC

**Comment by ResonantFilter** [comment] 2021-04-28 11:21
Thanks i did not see issue #49, I understand that would be a secondary feature. Thanks a lot anyways!

**Comment by D3SOX** [comment] 2021-04-28 11:22
@hmlendea I think a possible workaround would be to somehow do the login in the user's default browser and redirect them back to the application once they're logged in. Not entirely sure how I would implement that though
